title: Kennedy Kyalo
logo: assets/images/about.png
show_downloads: True
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

url: 'https://ken-warren.github.io/'
baseurl: 'top_UK_youtubers_2024/'
gem "github-pages", group: :jekyll_plugins
